BiskfarmWebApp/Controllers/RDSuperProfileController.cs
using Biskfarm.DAL;
using Biskfarm.DAL.Model;
using Biskfarm.Services;
using BiskfarmWebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BiskfarmWebApp.Controllers
{
    public class RDSuperProfileController : Controller
    {
        private readonly BiskfarmContext db;
        RDSSuperProfileServices rdsServices = new RDSSuperProfileServices();
        private IConfiguration configuration;

        public RDSuperProfileController(BiskfarmContext _db, IConfiguration _con)
        {
            db = _db;
            configuration = _con;   

        }
        public IActionResult Index()
        {
			if (HttpContext.Session.GetString("UserName") != null)
			{
                ViewBag.UserName = HttpContext.Session.GetString("UserName");
                ViewBag.SO_ID = HttpContext.Session.GetString("SO_ID");
                return View(rdsServices.GetAll(db, ViewBag.SO_ID));
			}
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        public IActionResult RDSuperProfileList()
        {
            return View();
        }

        public IActionResult View(int id)
        {
            var rds= rdsServices.GetProfileById(db,id,GetConnectionString());
            return View(rds);
        }
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("UserName") != null)
            {
                
                ViewBag.UserName = HttpContext.Session.GetString("UserName");
                ViewBag.SO_ID = HttpContext.Session.GetString("SO_ID");
                var inputServices = rdsServices.GetRDSSuperProfileInputParameters(db, ViewBag.SO_ID,GetConnectionString());

                return View(inputServices);
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }

        private string GetConnectionString()
        {
            return this.configuration.GetConnectionString("dbBiskfarm");
        }

        [HttpPost]
        public IActionResult Create(RDSSuperProfileVM profile)
        {
            //foreach(var dst in  distributorData)
            //{

            //}
            //var inputServices = rdsServices.GetRDSSuperProfileInputParameters(db);

            return View();
        }

        [HttpPost]
        public JsonResult GetData(RDSSuperProfileVM profileVM)
        {
            bool rel= rdsServices.SaveRDSSuperProfile(db, profileVM);
            if(rel)
            {
                return Json("Data Saved");
            }
            else
            {
                return Json("Error");
            }
            
        }
    }
}

BiskfarmWebApp/Views/RDSuperProfile/Index.cshtml
@using Biskfarm.DAL.Model
@using Biskfarm.Services
@{
    Layout = "~/Views/Shared/_LayoutForms.cshtml";
    //Layout = null;
}

@model List<RDS_SuperProfile>

@* @section userName {

    <div class="info">
        <a href="#" class="d-block">Alexander Pierce</a>
    </div>
} *@

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                  <h1>RDS SuperProfile</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">RDS Super Profile</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Create", "RDSuperProfile")'">Create</button>
            </div>
                <div class="card-header">
                    <h3 class="card-title">RDS Super Profile List</h3>
                </div>
            <div class="card-body">
                <table id="routeSales" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Principal Co.</th>
                            <th>Date Of Entry</th>
                            <th>Proprietor Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                @foreach (var mdl in Model)
                {
                            <tr>
                                <td>@mdl.principalCo</td>
                                <td>@mdl.dateOfEntry</td>
                                <td>@mdl.nameOfProp1</td>
                                <td> <button class="btnView btn-xs btn-warning" onclick="location.href='@Url.Action("View", "RDSuperProfile",new {id=mdl.rdsSuperProfileId})'"><i class="fas fa-edit"></i></button></td>
                            </tr>
                }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Principal Co.</th>
                            <th>Date Of Entry</th>
                            <th>Proprietor Name</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
</section>

BiskfarmWebApp/Views/RDSuperProfile/RDSuperProfileList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>RDS Super Profile</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home">Home</a></li>
                    <li class="breadcrumb-item active">RDS Super Profile</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">RDS Super Profile List</h3>
                    </div>

                    <div class="card-body">
                        <button type="button" id="btnNew" class="btn btn-secondary">Add New</button>
                    </div>

                    <div class="col-xl-12" id="createContainer">


                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

<script>

    $("#btnNew").click(function () {

        $.ajax({
            type: "GET",
            url: '/RDSuperProfile/Create',
        })
            .done(function (response) {
                $("#createContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("fail");
            });

    });

</script>