BiskfarmWebApp/Components/HeirarchyListViewComponent.cs
using Biskfarm.DAL;
using Biskfarm.Services;
using Microsoft.AspNetCore.Mvc;

namespace BiskfarmWebApp.Components
{
    public class HeirarchyListViewComponent : ViewComponent
    {
        private readonly BiskfarmContext db;
        HierarchyServices services=new HierarchyServices();
        public HeirarchyListViewComponent(BiskfarmContext _db)
        {
            db= _db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var hierarchies = services.GetAllHierarchy(db);
            return View(hierarchies);
            //return View();
        }
    }
}

BiskfarmWebApp/Controllers/HierarchyController.cs
using Biskfarm.DAL;
using Biskfarm.DAL.Model;
using Biskfarm.Services;
using Microsoft.AspNetCore.Mvc;

namespace BiskfarmWebApp.Controllers
{
    public class HierarchyController : Controller
    {
        private readonly BiskfarmContext db;
        HierarchyServices services=new HierarchyServices();

        public HierarchyController(BiskfarmContext context)
        {
            db= context;
        }
        public IActionResult Index()
        {
            var hierarchies = services.GetAllHierarchy(db);
            return View(hierarchies);
        }


        public IActionResult Create()
        {
            return View();   
        }

        [HttpPost]
        public IActionResult Create(RDS_Hierarchy hierarchy)
        {
            services.AddHierarchy(hierarchy,db);

            return Json("Success");
        }
    }
}

BiskfarmWebApp/Views/Hierarchy/Create.cshtml
@{
    Layout = "~/Views/Shared/_LayoutForms.cshtml";
    //Layout = null;
}

<section class="content">

<div class="col-md-12" style="margin-bottom:10px;margin-top:10px">
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Create Hierarchy</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <form role="form" class="parsley-examples" id="hierarchyCreate">
                <div class="form-group row">
                    <label>Enter Hierarchy Level</label>
                    <input type="text" class="form-control" placeholder="Enter Hierarchy Level" id="hierarchyName" name="hierarchyName">
                </div>               
                <div class="form-group row">
                    <div class="col-8 offset-4">
                        <button type="button" id="btnSave" class="btn btn-primary waves-effect waves-light mr-1">
                            Submit
                        </button>
                        <button type="reset" id="btnCancel"
                                class="btn btn-secondary waves-effect">
                            Cancel
                        </button>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>


</section>


@section Scripts {
<script>
        $("#btnSave").click(function () {
            console.log($("#hierarchyCreate").serialize());
            $.ajax({
                type: "POST",
                url: '/Hierarchy/Create',
                data: $("#hierarchyCreate").serialize()
            })
                .done(function (response) {
                    alert("Hierarchy Level saved.");
                    $("#hierarchyName").val("");
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("fail");
                });


        });

        $("#btnCancel").click(function () {
            $("#hierarchyName").val("");
        })
</script>
}

BiskfarmWebApp/Views/Hierarchy/Index.cshtml
@* <div>
    <div id="tableContainer">
        @await Component.InvokeAsync("HeirarchyList");
    </div>
</div> *@

@{
    Layout = "~/Views/Shared/_LayoutForms.cshtml";
    //Layout = null;
}

@using Biskfarm.DAL.Model
@model List<RDS_Hierarchy>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="card-body">
                <button class="btn btn-secondary" onclick="location.href='@Url.Action("Create", "Hierarchy")'">Create</button>
            </div>
            <div class="col-12">
                <div class="card card-warning col-md-6" id="createContainer">

                    <!-- /.card-body -->
                </div>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Hierarchy List</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Hierarchy Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Count != 0)
                                {
                                    foreach (var m in Model)
                                    {
                                        <tr>
                                            <td>@m.hierarchyName</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Hierarchy Level</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>



@section Scripts {
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });

        // $(document).ready(function () {
        //     $("#btnNew").click(function () {
        //         $.ajax({
        //             type: "GET",
        //             url: '/Hierarchy/Create',
        //         })
        //             .done(function (response) {
        //                 $("#createContainer").html(response);
        //             })
        //             .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        //                 alert("fail");
        //             });

        //     });
        // });

        

    </script>
}